language: c
compiler:
  - gcc
  - clang
services:
  - redis-server
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
script:
  - rake test
notifications:
  irc:
    channels:
      - "irc.freenode.org#backdoor-log"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - secure: "B40Dmvt0JkAQA/dfhUP+NYFI37pBkxRBrc+XudT2bCilj3Z99B1l36oHxfy9Ate01yDPNrq7pCT2WGmLhfumXwwiucxcSpCg06D563IPZsrc4fnhqwTyWzTu8YUvEYgUONG5gokPOAIP9yGXNbyel9+wPVZitOkVTPRrm3PNbiE="

