language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf redis-server
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-redis/build_config.rb .
script: 
  - rake test
notifications:
  irc:
    channels:
      - "irc.freenode.org#backdoor-log"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"

